name: Build && Publish

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/otobrglez/tttm-randy:latest

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          known_hosts: unnecessary
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa_og_events
          config: |
            Host low
              User oto
              Hostname oto.srv4all.net
              IdentityFile ~/.ssh/id_rsa_og_events
              StrictHostKeyChecking no
              ConnectTimeout 60
              ConnectionAttempts 2
          if_key_exists: fail

      - name: Deploy to production
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          export DOCKER_HOST="ssh://low"
          ./bin/randy-prod.sh pull && \
            ./bin/randy-prod.sh up -d --remove-orphans
